name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # A common action for this purpose
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Or ./build, ./dist if you have a build step
